name: Trigger auto deployment for d-ca-blog-jd-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ DEV ]
    paths:
    - 'src/main/docker/Dockerfile.jvm/**'
    - '.github/workflows/d-ca-blog-jd-dev-AutoDeployTrigger-d0e7ae9d-3dd8-4c74-975c-672337b67b19.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: jessicasblog.azurecr.io
          username: ${{ secrets.DCABLOGJDDEV_REGISTRY_USERNAME }}
          password: ${{ secrets.DCABLOGJDDEV_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jessicasblog.azurecr.io/d-ca-blog-jd-dev:${{ github.sha }}
          file: src/main/docker/Dockerfile.jvm/Dockerfile
          context: src/main/docker/Dockerfile.jvm/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DCABLOGJDDEV_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n d-ca-blog-jd-dev -g d-rg-blog-jd --server jessicasblog.azurecr.io --username  ${{ secrets.DCABLOGJDDEV_REGISTRY_USERNAME }} --password ${{ secrets.DCABLOGJDDEV_REGISTRY_PASSWORD }}
            az containerapp update -n d-ca-blog-jd-dev -g d-rg-blog-jd --image jessicasblog.azurecr.io/d-ca-blog-jd-dev:${{ github.sha }}
