name: Build and Deploy Docker image to Azure Container App
on:
  push:
    branches:
      - DEV
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: jessicasblog.azurecr.io/blog_backend_jd
      IMAGE_TAG: DEV
      RESSOURCE_GROUP: d-rg-blog-jd
      REVISION: d-ca-blog-jd-dev--dev
      QUARKUS_PROFILE: dev
      QUARKUS_DATASOURCE_USERNAME: dbuser
      QUARKUS_DATASOURCE_PASSWORD: dbuser
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://d-mysql-blog-jd.mysql.database.azure.com:3306/blogdb
      QUARKUS_SMALLRYE_OPENAPI_INFO_TITLE: DEV Blog API
      QUARKUS_CONTAINER_IMAGE_NAME: blog-backend-dev
      QUARKUS_CONTAINER_IMAGE_TAG: latest-dev
      AZURE_WEBAPP_NAME: d-ca-blog-jd-dev
      AZURE_RESOURCE_GROUP: d-rg-blog-jd
      AZURE_IMAGE_NAME: jessicasblog.azurecr.io/blog_backend_jd
      AZURE_IMAGE_TAG: DEV
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DCABLOGJDDEV_AZURE_CREDENTIALS }}
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: jessicasblog.azurecr.io
          username: '${{secrets.ACR_USERNAME}}'
          password: '${{secrets.ACR_PASSWORD}}'
      - name: Replace environment variables in application.properties file
        run: >-
          sed -i 's|\%dev.quarkus.smallrye-openapi.info-title=DEV Blog
          API|\%dev.quarkus.smallrye-openapi.info-title='"${QUARKUS_SMALLRYE_OPENAPI_INFO_TITLE}"'|g;
          s|\%dev.quarkus.container-image.name=blog-backend-dev|\%dev.quarkus.container-image.name='"${QUARKUS_CONTAINER_IMAGE_NAME}"'|g;
          s|\%dev.quarkus.container-image.tag=latest-dev|\%dev.quarkus.container-image.tag='"${QUARKUS_CONTAINER_IMAGE_TAG}"'|g'
          src/main/resources/application.properties
      - name: Build Docker image
        run: >-
          docker build --file src/main/docker/Dockerfile.jvm
          --build-arg QUARKUS_PROFILE=${{env.QUARKUS_PROFILE}}
          --build-arg QUARKUS_DATASOURCE_USERNAME=${{env.QUARKUS_DATASOURCE_USERNAME}}
          --build-arg QUARKUS_DATASOURCE_PASSWORD=${{env.QUARKUS_DATASOURCE_PASSWORD}}
          --build-arg QUARKUS_DATASOURCE_JDBC_URL=${{env.QUARKUS_DATASOURCE_JDBC_URL}}
          -t ${{env.AZURE_IMAGE_NAME}}:${{env.AZURE_IMAGE_TAG}} .
      - name: Push Docker image to Azure Container Registry
        run: 
          docker push ${{env.AZURE_IMAGE_NAME}}:${{env.AZURE_IMAGE_TAG}}
      - name: Deploy to Azure Container App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n d-ca-blog-jd-dev -g d-rg-blog-jd --image jessicasblog.azurecr.io/blog_backend_jd:DEV
            az containerapp revision restart -n d-ca-blog-jd-dev -g d-rg-blog-jd --revision d-ca-blog-jd-dev--yq4nk1o

